export const FormLocations = {
  en: [
    { key: 'AF', value: 'Afghanistan' },
    { key: 'AL', value: 'Albania' },
    { key: 'DZ', value: 'Algeria' },
    { key: 'AS', value: 'American Samoa' },
    { key: 'AD', value: 'Andorra' },
    { key: 'AO', value: 'Angola' },
    { key: 'AI', value: 'Anguilla' },
    { key: 'AQ', value: 'Antarctica' },
    { key: 'AG', value: 'Antigua/Barbuda' },
    { key: 'AR', value: 'Argentina' },
    { key: 'AM', value: 'Armenia' },
    { key: 'AW', value: 'Aruba' },
    { key: 'AU', value: 'Australia' },
    { key: 'AT', value: 'Austria' },
    { key: 'AZ', value: 'Azerbaijan' },
    { key: 'BS', value: 'Bahamas' },
    { key: 'BH', value: 'Bahrain' },
    { key: 'BD', value: 'Bangladesh' },
    { key: 'BB', value: 'Barbados' },
    { key: 'BY', value: 'Belarus' },
    { key: 'BE', value: 'Belgium' },
    { key: 'BZ', value: 'Belize' },
    { key: 'BJ', value: 'Benin' },
    { key: 'BM', value: 'Bermuda' },
    { key: 'BT', value: 'Bhutan' },
    { key: 'BO', value: 'Bolivia' },
    { key: 'BA', value: 'Bosnia and Herzegovina' },
    { key: 'BW', value: 'Botswana' },
    { key: 'BV', value: 'Bouvet Island' },
    { key: 'BR', value: 'Brazil' },
    { key: 'IO', value: 'British Indian Ocean Territory' },
    { key: 'WI', value: 'British West Indies' },
    { key: 'BN', value: 'Brunei Darussalam' },
    { key: 'BG', value: 'Bulgaria' },
    { key: 'BF', value: 'Burkina Faso' },
    { key: 'BU', value: 'Burma' },
    { key: 'BI', value: 'Burundi' },
    { key: 'KH', value: 'Cambodia' },
    { key: 'CM', value: 'Cameroon' },
    { key: 'CA', value: 'Canada' },
    { key: 'CV', value: 'Cape Verde' },
    { key: 'KY', value: 'Cayman Islands' },
    { key: 'CF', value: 'Central Africa' },
    { key: 'TD', value: 'Chad' },
    { key: 'CL', value: 'Chile' },
    { key: 'CN', value: 'Chinese Mainland' },
    { key: 'CX', value: 'Christmas Island' },
    { key: 'CC', value: 'Cocos Islands' },
    { key: 'CO', value: 'Colombia' },
    { key: 'KM', value: 'Comoros' },
    { key: 'CG', value: 'Congo' },
    { key: 'CK', value: 'Cook Islands' },
    { key: 'CR', value: 'Costa Rica' },
    { key: 'CI', value: 'Cote D"Ivoire' },
    { key: 'HR', value: 'Croatia' },
    { key: 'CU', value: 'Cuba' },
    { key: 'CY', value: 'Cyprus' },
    { key: 'CZ', value: 'Czech Republic' },
    { key: 'DK', value: 'Denmark' },
    { key: 'DJ', value: 'Djibouti' },
    { key: 'DM', value: 'Dominica' },
    { key: 'DO', value: 'Dominican Republic' },
    { key: 'TP', value: 'East Timor' },
    { key: 'EC', value: 'Ecuador' },
    { key: 'EG', value: 'Egypt' },
    { key: 'SV', value: 'El Salvador' },
    { key: 'GQ', value: 'Equatorial Guinea' },
    { key: 'ER', value: 'Eritrea' },
    { key: 'EE', value: 'Estonia' },
    { key: 'ET', value: 'Ethiopia' },
    { key: 'FO', value: 'Faroe Islands' },
    { key: 'FK', value: 'Falkland Islands' },
    { key: 'FJ', value: 'Fiji' },
    { key: 'FI', value: 'Finland' },
    { key: 'FR', value: 'France' },
    { key: 'PF', value: 'French Polynesia' },
    { key: 'TF', value: 'French Southern Territories' },
    { key: 'GA', value: 'Gabon' },
    { key: 'GM', value: 'Gambia' },
    { key: 'XA', value: 'Gaza' },
    { key: 'GE', value: 'Georgia' },
    { key: 'DE', value: 'Germany' },
    { key: 'GH', value: 'Ghana' },
    { key: 'GI', value: 'Gibraltar' },
    { key: 'GR', value: 'Greece' },
    { key: 'GL', value: 'Greenland' },
    { key: 'GD', value: 'Grenada' },
    { key: 'GP', value: 'Guadeloupe' },
    { key: 'GU', value: 'Guam' },
    { key: 'GT', value: 'Guatemala' },
    { key: 'GF', value: 'Guiana' },
    { key: 'GN', value: 'Guinea' },
    { key: 'GW', value: 'Guinea Bissau' },
    { key: 'GY', value: 'Guyana' },
    { key: 'HT', value: 'Haiti' },
    { key: 'HM', value: 'Heard Island & McDonald Islands' },
    { key: 'XH', value: 'Held Territories' },
    { key: 'HN', value: 'Honduras' },
    { key: 'HK', value: 'Hong Kong SAR' },
    { key: 'HU', value: 'Hungary' },
    { key: 'IS', value: 'Iceland' },
    { key: 'IN', value: 'India' },
    { key: 'XI', value: 'Indian Ocean Islands' },
    { key: 'ID', value: 'Indonesia' },
    { key: 'IR', value: 'Iran' },
    { key: 'IQ', value: 'Iraq' },
    { key: 'IE', value: 'Ireland' },
    { key: 'IL', value: 'Israel' },
    { key: 'IT', value: 'Italy' },
    { key: 'JM', value: 'Jamaica' },
    { key: 'JP', value: 'Japan' },
    { key: 'JO', value: 'Jordan' },
    { key: 'KZ', value: 'Kazakhstan' },
    { key: 'KE', value: 'Kenya' },
    { key: 'KI', value: 'Kiribati' },
    { key: 'KR', value: 'Korea' },
    { key: 'KW', value: 'Kuwait' },
    { key: 'KG', value: 'Kyrgyzstan' },
    { key: 'LA', value: 'Laos' },
    { key: 'LV', value: 'Latvia' },
    { key: 'LB', value: 'Lebanon' },
    { key: 'LS', value: 'Lesotho' },
    { key: 'LR', value: 'Liberia' },
    { key: 'LY', value: 'Libya' },
    { key: 'LI', value: 'Liechtenstein' },
    { key: 'LT', value: 'Lithuania' },
    { key: 'LU', value: 'Luxembourg' },
    { key: 'MO', value: 'Macau SAR' },
    { key: 'MK', value: 'Macedonia' },
    { key: 'MG', value: 'Madagascar' },
    { key: 'MW', value: 'Malawi' },
    { key: 'MY', value: 'Malaysia' },
    { key: 'MV', value: 'Maldives' },
    { key: 'ML', value: 'Mali' },
    { key: 'MT', value: 'Malta' },
    { key: 'MH', value: 'Marshall Islands' },
    { key: 'MQ', value: 'Martinique' },
    { key: 'MR', value: 'Mauritania' },
    { key: 'MU', value: 'Mauritius' },
    { key: 'YT', value: 'Mayotte' },
    { key: 'MX', value: 'Mexico' },
    { key: 'FM', value: 'Micronesia' },
    { key: 'MD', value: 'Moldova' },
    { key: 'MC', value: 'Monaco' },
    { key: 'MN', value: 'Mongolia' },
    { key: 'MS', value: 'Montserrat' },
    { key: 'MA', value: 'Morocco' },
    { key: 'MZ', value: 'Mozambique' },
    { key: 'MM', value: 'Myanmar' },
    { key: 'NA', value: 'Namibia' },
    { key: 'NR', value: 'Nauru' },
    { key: 'NP', value: 'Nepal' },
    { key: 'NL', value: 'Netherlands' },
    { key: 'AN', value: 'Netherlands Antilles' },
    { key: 'NC', value: 'New Caledonia' },
    { key: 'NZ', value: 'New Zealand' },
    { key: 'NI', value: 'Nicaragua' },
    { key: 'NE', value: 'Niger' },
    { key: 'NG', value: 'Nigeria' },
    { key: 'NU', value: 'Niue' },
    { key: 'NF', value: 'Norfolk Island' },
    { key: 'KP', value: 'North Korea' },
    { key: 'XB', value: 'Northern Ireland' },
    { key: 'MP', value: 'Northern Mariana Islands' },
    { key: 'NO', value: 'Norway' },
    { key: 'OM', value: 'Oman' },
    { key: 'PK', value: 'Pakistan' },
    { key: 'PW', value: 'Palau' },
    { key: 'PA', value: 'Panama' },
    { key: 'PG', value: 'Papua New Guinea' },
    { key: 'PY', value: 'Paraguay' },
    { key: 'PE', value: 'Peru' },
    { key: 'PH', value: 'Philippines' },
    { key: 'PN', value: 'Pitcairn' },
    { key: 'PL', value: 'Poland' },
    { key: 'PT', value: 'Portugal' },
    { key: 'PR', value: 'Puerto Rico' },
    { key: 'QA', value: 'Qatar' },
    { key: 'RE', value: 'Reunion' },
    { key: 'RO', value: 'Romania' },
    { key: 'RU', value: 'Russia' },
    { key: 'RW', value: 'Rwanda' },
    { key: 'LC', value: 'Saint Lucia' },
    { key: 'SM', value: 'San Marino' },
    { key: 'ST', value: 'Sao Tome And Principe' },
    { key: 'SA', value: 'Saudi Arabia' },
    { key: 'SN', value: 'Senegal' },
    { key: 'SC', value: 'Seychelles' },
    { key: 'SL', value: 'Sierra Leone' },
    { key: 'SG', value: 'Singapore' },
    { key: 'SK', value: 'Slovak Republic' },
    { key: 'SI', value: 'Slovenia' },
    { key: 'SB', value: 'Solomon Islands' },
    { key: 'SO', value: 'Somalia' },
    { key: 'ZA', value: 'South Africa' },
    { key: 'GS', value: 'South Georgia' },
    { key: 'ES', value: 'Spain' },
    { key: 'LK', value: 'Sri Lanka' },
    { key: 'SH', value: 'St. Helena' },
    { key: 'KN', value: 'St. Kitts & Nevis' },
    { key: 'PM', value: 'St. Pierre' },
    { key: 'VC', value: 'St. Vincent & The Grenadine' },
    { key: 'SD', value: 'Sudan' },
    { key: 'SR', value: 'Suriname' },
    { key: 'SJ', value: 'Svalbard & Jan Mayen Islands' },
    { key: 'SZ', value: 'Swaziland' },
    { key: 'SE', value: 'Sweden' },
    { key: 'CH', value: 'Switzerland' },
    { key: 'SY', value: 'Syria' },
    { key: 'TW', value: 'Taiwan China' },
    { key: 'TJ', value: 'Tajikistan' },
    { key: 'TZ', value: 'Tanzania' },
    { key: 'TH', value: 'Thailand' },
    { key: 'TG', value: 'Togo' },
    { key: 'TK', value: 'Tokelau' },
    { key: 'TO', value: 'Tonga' },
    { key: 'TT', value: 'Trinidad And Tobago' },
    { key: 'TN', value: 'Tunisia' },
    { key: 'TR', value: 'Turkey' },
    { key: 'TM', value: 'Turkmenistan' },
    { key: 'TC', value: 'Turks And Caicos Islands' },
    { key: 'TV', value: 'Tuvalu' },
    { key: 'UM', value: 'U.S. Minor Outlying Islands' },
    { key: 'UG', value: 'Uganda' },
    { key: 'UA', value: 'Ukraine' },
    { key: 'AE', value: 'United Arab Emirates' },
    { key: 'GB', value: 'United Kingdom' },
    { key: 'US', value: 'United States' },
    { key: 'UY', value: 'Uruguay' },
    { key: 'UZ', value: 'Uzbekistan' },
    { key: 'VU', value: 'Vanuatu' },
    { key: 'VA', value: 'Vatican City State' },
    { key: 'VE', value: 'Venezuela' },
    { key: 'VN', value: 'Vietnam' },
    { key: 'VG', value: 'Virgin Islands (British)' },
    { key: 'VI', value: 'Virgin Islands (U.S.)' },
    { key: 'WF', value: 'Wallis & Futuna Island' },
    { key: 'EH', value: 'Western Sahara' },
    { key: 'WS', value: 'Western Samoa' },
    { key: 'YE', value: 'Yemen' },
    { key: 'YU', value: 'Yugoslavia' },
    { key: 'ZM', value: 'Zambia' },
    { key: 'ZW', value: 'Zimbabwe' },
  ],
  'zh-HK': [
    { key: 'AF', value: '阿富汗' },
    { key: 'AL', value: '阿爾巴尼亞' },
    { key: 'DZ', value: '阿爾及利亞' },
    { key: 'AS', value: '美屬薩摩亞' },
    { key: 'AD', value: '安道爾' },
    { key: 'AO', value: '安哥拉' },
    { key: 'AI', value: '安圭拉' },
    { key: 'AQ', value: '南極洲' },
    { key: 'AG', value: '安提瓜和巴布達' },
    { key: 'AR', value: '阿根廷' },
    { key: 'AM', value: '亞美尼亞' },
    { key: 'AW', value: '阿魯巴' },
    { key: 'AU', value: '澳洲' },
    { key: 'AT', value: '奧地利' },
    { key: 'AZ', value: '阿塞拜疆' },
    { key: 'BS', value: '巴哈馬' },
    { key: 'BH', value: '巴林' },
    { key: 'BD', value: '孟加拉' },
    { key: 'BB', value: '巴巴多斯' },
    { key: 'BY', value: '白俄羅斯' },
    { key: 'BE', value: '比利時' },
    { key: 'BZ', value: '伯利茲' },
    { key: 'BJ', value: '貝寧' },
    { key: 'BM', value: '百慕達' },
    { key: 'BT', value: '不丹' },
    { key: 'BO', value: '玻利維亞' },
    { key: 'BA', value: '波斯尼亞和黑塞哥維那' },
    { key: 'BW', value: '博茨瓦納' },
    { key: 'BV', value: '布威島' },
    { key: 'BR', value: '巴西' },
    { key: 'IO', value: '英屬印度洋領地' },
    { key: 'WI', value: '英屬西印度群島' },
    { key: 'BN', value: '文萊達魯薩蘭國' },
    { key: 'BG', value: '保加利亞' },
    { key: 'BF', value: '布基納法索' },
    { key: 'BU', value: '緬甸' },
    { key: 'BI', value: '蒲隆地' },
    { key: 'KH', value: '柬埔寨' },
    { key: 'CM', value: '喀麥隆' },
    { key: 'CA', value: '加拿大' },
    { key: 'CV', value: '佛得角' },
    { key: 'KY', value: '開曼群島' },
    { key: 'CF', value: '中非共和國' },
    { key: 'TD', value: '乍得' },
    { key: 'CL', value: '智利' },
    { key: 'CN', value: '中國內地' },
    { key: 'CX', value: '聖誕島' },
    { key: 'CC', value: '科科斯群島' },
    { key: 'CO', value: '哥倫比亞' },
    { key: 'KM', value: '科摩羅' },
    { key: 'CG', value: '剛果' },
    { key: 'CK', value: '庫克群島' },
    { key: 'CR', value: '哥斯達黎加' },
    { key: 'CI', value: '科特迪瓦' },
    { key: 'HR', value: '克羅地亞' },
    { key: 'CU', value: '古巴' },
    { key: 'CY', value: '塞浦路斯' },
    { key: 'CZ', value: '捷克' },
    { key: 'DK', value: '丹麥' },
    { key: 'DJ', value: '吉布提' },
    { key: 'DM', value: '多米尼克' },
    { key: 'DO', value: '多明尼加共和國' },
    { key: 'TP', value: '東帝汶' },
    { key: 'EC', value: '厄瓜多爾' },
    { key: 'EG', value: '埃及' },
    { key: 'SV', value: '薩爾瓦多' },
    { key: 'GQ', value: '赤道幾內亞' },
    { key: 'ER', value: '厄立特里亞' },
    { key: 'EE', value: '愛沙尼亞' },
    { key: 'ET', value: '埃塞俄比亞' },
    { key: 'FO', value: '法羅群島' },
    { key: 'FK', value: '马尔维纳斯群岛' },
    { key: 'FJ', value: '斐濟' },
    { key: 'FI', value: '芬蘭' },
    { key: 'FR', value: '法國' },
    { key: 'PF', value: '法属波利尼西亚' },
    { key: 'TF', value: '法屬南部和南極領地' },
    { key: 'GA', value: '加蓬' },
    { key: 'GM', value: '岡比亞' },
    { key: 'XA', value: '加沙' },
    { key: 'GE', value: '格魯吉亞' },
    { key: 'DE', value: '德國' },
    { key: 'GH', value: '加納' },
    { key: 'GI', value: '直布羅陀' },
    { key: 'GR', value: '希臘' },
    { key: 'GL', value: '格陵蘭' },
    { key: 'GD', value: '格林納達' },
    { key: 'GP', value: '瓜德羅普' },
    { key: 'GU', value: '關島' },
    { key: 'GT', value: '危地馬拉' },
    { key: 'GF', value: '幾內亞' },
    { key: 'GN', value: '幾內亞' },
    { key: 'GW', value: '幾內亞比紹' },
    { key: 'GY', value: '圭亞那' },
    { key: 'HT', value: '海地' },
    { key: 'HM', value: '赫德島和麥克唐納群島' },
    { key: 'XH', value: '佔領地區' },
    { key: 'HN', value: '洪都拉斯' },
    { key: 'HK', value: '香港特別行政區' },
    { key: 'HU', value: '匈牙利' },
    { key: 'IS', value: '冰島' },
    { key: 'IN', value: '印度' },
    { key: 'XI', value: '印度洋群島' },
    { key: 'ID', value: '印尼' },
    { key: 'IR', value: '伊朗' },
    { key: 'IQ', value: '伊拉克' },
    { key: 'IE', value: '愛爾蘭' },
    { key: 'IL', value: '以色列' },
    { key: 'IT', value: '意大利' },
    { key: 'JM', value: '牙買加' },
    { key: 'JP', value: '日本' },
    { key: 'JO', value: '約旦' },
    { key: 'KZ', value: '哈薩克斯坦' },
    { key: 'KE', value: '肯尼亞' },
    { key: 'KI', value: '基里巴斯' },
    { key: 'KR', value: '大韓民國' },
    { key: 'KW', value: '科威特' },
    { key: 'KG', value: '吉爾吉斯斯坦' },
    { key: 'LA', value: '老撾人民民主共和國' },
    { key: 'LV', value: '拉脫維亞' },
    { key: 'LB', value: '黎巴嫩' },
    { key: 'LS', value: '萊索托' },
    { key: 'LR', value: '利比里亞' },
    { key: 'LY', value: '阿拉伯利比亞民眾國' },
    { key: 'LI', value: '列支敦士登' },
    { key: 'LT', value: '立陶宛' },
    { key: 'LU', value: '盧森堡' },
    { key: 'MO', value: '澳門特別行政區' },
    { key: 'MK', value: '馬其頓共和國' },
    { key: 'MG', value: '馬達加斯加' },
    { key: 'MW', value: '馬拉維' },
    { key: 'MY', value: '馬來西亞' },
    { key: 'MV', value: '馬爾代夫' },
    { key: 'ML', value: '馬里' },
    { key: 'MT', value: '馬耳他' },
    { key: 'MH', value: '馬紹爾群島' },
    { key: 'MQ', value: '馬提尼克島' },
    { key: 'MR', value: '毛里塔尼亞' },
    { key: 'MU', value: '毛里求斯' },
    { key: 'YT', value: '馬約特島' },
    { key: 'MX', value: '墨西哥' },
    { key: 'FM', value: '密克羅尼西亞' },
    { key: 'MD', value: '摩爾多瓦共和國' },
    { key: 'MC', value: '摩納哥' },
    { key: 'MN', value: '蒙古' },
    { key: 'MS', value: '蒙特塞拉特' },
    { key: 'MA', value: '摩洛哥' },
    { key: 'MZ', value: '莫桑比克' },
    { key: 'MM', value: '緬甸' },
    { key: 'NA', value: '納米比亞' },
    { key: 'NR', value: '瑙魯' },
    { key: 'NP', value: '尼泊爾' },
    { key: 'NL', value: '荷蘭' },
    { key: 'AN', value: '荷屬安的列斯' },
    { key: 'NC', value: '新喀裡多尼亞' },
    { key: 'NZ', value: '新西蘭' },
    { key: 'NI', value: '尼加拉瓜' },
    { key: 'NE', value: '尼日爾' },
    { key: 'NG', value: '尼日利亞' },
    { key: 'NU', value: '紐埃' },
    { key: 'NF', value: '諾福克島' },
    { key: 'KP', value: '朝鮮民主主義人民共和國' },
    { key: 'XB', value: '北愛爾蘭' },
    { key: 'MP', value: '北馬里亞納群島' },
    { key: 'NO', value: '挪威' },
    { key: 'OM', value: '阿曼' },
    { key: 'PK', value: '巴基斯坦' },
    { key: 'PW', value: '帕勞' },
    { key: 'PA', value: '巴拿馬' },
    { key: 'PG', value: '巴布亞新幾內亞' },
    { key: 'PY', value: '巴拉圭' },
    { key: 'PE', value: '秘魯' },
    { key: 'PH', value: '菲律賓' },
    { key: 'PN', value: '皮特凱恩' },
    { key: 'PL', value: '波蘭' },
    { key: 'PT', value: '葡萄牙' },
    { key: 'PR', value: '波多黎各' },
    { key: 'QA', value: '卡塔爾' },
    { key: 'RE', value: '留尼汪' },
    { key: 'RO', value: '羅馬尼亞' },
    { key: 'RU', value: '俄羅斯' },
    { key: 'RW', value: '盧旺達' },
    { key: 'LC', value: '聖盧西亞' },
    { key: 'SM', value: '聖馬利諾' },
    { key: 'ST', value: '聖多美和普林西比' },
    { key: 'SA', value: '沙特阿拉伯' },
    { key: 'SN', value: '塞內加爾' },
    { key: 'SC', value: '塞舌爾' },
    { key: 'SL', value: '塞拉利昂' },
    { key: 'SG', value: '新加坡' },
    { key: 'SK', value: '斯洛伐克共和國' },
    { key: 'SI', value: '斯洛文尼亞' },
    { key: 'SB', value: '索羅門群島' },
    { key: 'SO', value: '索馬里' },
    { key: 'ZA', value: '南非' },
    { key: 'GS', value: '南喬治亞' },
    { key: 'ES', value: '西班牙' },
    { key: 'LK', value: '斯里蘭卡' },
    { key: 'SH', value: '聖赫勒拿島' },
    { key: 'KN', value: '聖克里斯多福及尼維斯' },
    { key: 'PM', value: '聖皮埃爾' },
    { key: 'VC', value: '聖文森及格瑞那丁' },
    { key: 'SD', value: '蘇丹' },
    { key: 'SR', value: '蘇里南' },
    { key: 'SJ', value: '斯瓦爾巴和揚馬延' },
    { key: 'SZ', value: '史瓦濟蘭' },
    { key: 'SE', value: '瑞典' },
    { key: 'CH', value: '瑞士' },
    { key: 'SY', value: '阿拉伯敘利亞共和國' },
    { key: 'TW', value: '中國台灣' },
    { key: 'TJ', value: '塔吉克斯坦' },
    { key: 'TZ', value: '坦桑尼亞' },
    { key: 'TH', value: '泰國' },
    { key: 'TG', value: '多哥' },
    { key: 'TK', value: '托克勞' },
    { key: 'TO', value: '東加' },
    { key: 'TT', value: '特立尼達和多巴哥' },
    { key: 'TN', value: '突尼斯' },
    { key: 'TR', value: '土耳其' },
    { key: 'TM', value: '土庫曼斯坦' },
    { key: 'TC', value: '特克斯和凱科斯群島' },
    { key: 'TV', value: '圖瓦盧' },
    { key: 'UM', value: '美國本土外小島嶼' },
    { key: 'UG', value: '烏干達' },
    { key: 'UA', value: '烏克蘭' },
    { key: 'AE', value: '阿拉伯聯合酋長國' },
    { key: 'GB', value: '英国' },
    { key: 'US', value: '美國' },
    { key: 'UY', value: '烏拉圭' },
    { key: 'UZ', value: '烏茲別克斯坦' },
    { key: 'VU', value: '瓦努阿圖' },
    { key: 'VA', value: '梵蒂岡城國' },
    { key: 'VE', value: '委內瑞拉' },
    { key: 'VN', value: '越南' },
    { key: 'VG', value: '英屬維京群島' },
    { key: 'VI', value: '美屬維京群島' },
    { key: 'WF', value: '瓦利斯和富圖納群島' },
    { key: 'EH', value: '西撒哈拉' },
    { key: 'WS', value: '薩摩亞' },
    { key: 'YE', value: '也門' },
    { key: 'YU', value: '南斯拉夫' },
    { key: 'ZM', value: '贊比亞' },
    { key: 'ZW', value: '津巴布韋' },
  ],
  'zh-CN': [
    { key: 'AF', value: '阿富汗' },
    { key: 'AL', value: '阿尔巴尼亚' },
    { key: 'DZ', value: '阿尔及利亚' },
    { key: 'AS', value: '美属萨摩亚' },
    { key: 'AD', value: '安道尔' },
    { key: 'AO', value: '安哥拉' },
    { key: 'AI', value: '安圭拉' },
    { key: 'AQ', value: '南极洲' },
    { key: 'AG', value: '安提瓜和巴布达' },
    { key: 'AR', value: '阿根廷' },
    { key: 'AM', value: '亚美尼亚' },
    { key: 'AW', value: '阿鲁巴' },
    { key: 'AU', value: '澳大利亚' },
    { key: 'AT', value: '奥地利' },
    { key: 'AZ', value: '阿塞拜疆' },
    { key: 'BS', value: '巴哈马' },
    { key: 'BH', value: '巴林' },
    { key: 'BD', value: '孟加拉' },
    { key: 'BB', value: '巴巴多斯' },
    { key: 'BY', value: '白俄罗斯' },
    { key: 'BE', value: '比利时' },
    { key: 'BZ', value: '伯利兹' },
    { key: 'BJ', value: '贝宁' },
    { key: 'BM', value: '百慕达' },
    { key: 'BT', value: '不丹' },
    { key: 'BO', value: '玻利维亚' },
    { key: 'BA', value: '波斯尼亚和黑塞哥维那' },
    { key: 'BW', value: '博茨瓦纳' },
    { key: 'BV', value: '布威岛' },
    { key: 'BR', value: '巴西' },
    { key: 'IO', value: '英属印度洋领地' },
    { key: 'WI', value: '英属西印度群岛' },
    { key: 'BN', value: '文莱达鲁萨兰国' },
    { key: 'BG', value: '保加利亚' },
    { key: 'BF', value: '布基纳法索' },
    { key: 'BU', value: '缅甸' },
    { key: 'BI', value: '蒲隆地' },
    { key: 'KH', value: '柬埔寨' },
    { key: 'CM', value: '喀麦隆' },
    { key: 'CA', value: '加拿大' },
    { key: 'CV', value: '佛得角' },
    { key: 'KY', value: '开曼群岛' },
    { key: 'CF', value: '中非共和国' },
    { key: 'TD', value: '乍得' },
    { key: 'CL', value: '智利' },
    { key: 'CN', value: '中国内地' },
    { key: 'CX', value: '圣诞岛' },
    { key: 'CC', value: '科科斯群岛' },
    { key: 'CO', value: '哥伦比亚' },
    { key: 'KM', value: '科摩罗' },
    { key: 'CG', value: '刚果' },
    { key: 'CK', value: '库克群岛' },
    { key: 'CR', value: '哥斯达黎加' },
    { key: 'CI', value: '科特迪瓦' },
    { key: 'HR', value: '克罗地亚' },
    { key: 'CU', value: '古巴' },
    { key: 'CY', value: '塞浦路斯' },
    { key: 'CZ', value: '捷克' },
    { key: 'DK', value: '丹麦' },
    { key: 'DJ', value: '吉布提' },
    { key: 'DM', value: '多米尼克' },
    { key: 'DO', value: '多明尼加共和国' },
    { key: 'TP', value: '东帝汶' },
    { key: 'EC', value: '厄瓜多尔' },
    { key: 'EG', value: '埃及' },
    { key: 'SV', value: '萨尔瓦多' },
    { key: 'GQ', value: '赤道几内亚' },
    { key: 'ER', value: '厄立特里亚' },
    { key: 'EE', value: '爱沙尼亚' },
    { key: 'ET', value: '埃塞俄比亚' },
    { key: 'FO', value: '法罗群岛' },
    { key: 'FK', value: '马尔维纳斯群岛' },
    { key: 'FJ', value: '斐济' },
    { key: 'FI', value: '芬兰' },
    { key: 'FR', value: '法国' },
    { key: 'PF', value: '法属波利尼西亚' },
    { key: 'TF', value: '法属南部和南极领地' },
    { key: 'GA', value: '加蓬' },
    { key: 'GM', value: '冈比亚' },
    { key: 'XA', value: '加沙' },
    { key: 'GE', value: '格鲁吉亚' },
    { key: 'DE', value: '德国' },
    { key: 'GH', value: '加纳' },
    { key: 'GI', value: '直布罗陀' },
    { key: 'GR', value: '希腊' },
    { key: 'GL', value: '格陵兰' },
    { key: 'GD', value: '格林纳达' },
    { key: 'GP', value: '瓜德罗普' },
    { key: 'GU', value: '关岛' },
    { key: 'GT', value: '危地马拉' },
    { key: 'GF', value: '几内亚' },
    { key: 'GN', value: '几内亚' },
    { key: 'GW', value: '几内亚比绍' },
    { key: 'GY', value: '圭亚那' },
    { key: 'HT', value: '海地' },
    { key: 'HM', value: '赫德岛和麦克唐纳群岛' },
    { key: 'XH', value: '占领地区' },
    { key: 'HN', value: '洪都拉斯' },
    { key: 'HK', value: '香港特别行政区' },
    { key: 'HU', value: '匈牙利' },
    { key: 'IS', value: '冰岛' },
    { key: 'IN', value: '印度' },
    { key: 'XI', value: '印度洋群岛' },
    { key: 'ID', value: '印度尼西亚' },
    { key: 'IR', value: '伊朗' },
    { key: 'IQ', value: '伊拉克' },
    { key: 'IE', value: '爱尔兰' },
    { key: 'IL', value: '以色列' },
    { key: 'IT', value: '意大利' },
    { key: 'JM', value: '牙买加' },
    { key: 'JP', value: '日本' },
    { key: 'JO', value: '約旦' },
    { key: 'KZ', value: '哈萨克斯坦' },
    { key: 'KE', value: '肯尼亚' },
    { key: 'KI', value: '基里巴斯' },
    { key: 'KR', value: '大韩民国' },
    { key: 'KW', value: '科威特' },
    { key: 'KG', value: '吉尔吉斯斯坦' },
    { key: 'LA', value: '老挝人民民主共和国' },
    { key: 'LV', value: '拉脱维亚' },
    { key: 'LB', value: '黎巴嫩' },
    { key: 'LS', value: '莱索托' },
    { key: 'LR', value: '利比里亚' },
    { key: 'LY', value: '阿拉伯利比亚民众国' },
    { key: 'LI', value: '列支敦士登' },
    { key: 'LT', value: '立陶宛' },
    { key: 'LU', value: '卢森堡' },
    { key: 'MO', value: '澳门特别行政区' },
    { key: 'MK', value: '马其顿共和国' },
    { key: 'MG', value: '马达加斯加' },
    { key: 'MW', value: '马拉维' },
    { key: 'MY', value: '马来西亚' },
    { key: 'MV', value: '马尔代夫' },
    { key: 'ML', value: '马里' },
    { key: 'MT', value: '马耳他' },
    { key: 'MH', value: '马绍尔群岛' },
    { key: 'MQ', value: '马提尼克岛' },
    { key: 'MR', value: '毛里塔尼亚' },
    { key: 'MU', value: '毛里求斯' },
    { key: 'YT', value: '马约特岛' },
    { key: 'MX', value: '墨西哥' },
    { key: 'FM', value: '密克罗尼西亚' },
    { key: 'MD', value: '摩尔多瓦共和国' },
    { key: 'MC', value: '摩纳哥' },
    { key: 'MN', value: '蒙古' },
    { key: 'MS', value: '蒙特塞拉特' },
    { key: 'MA', value: '摩洛哥' },
    { key: 'MZ', value: '莫桑比克' },
    { key: 'MM', value: '缅甸' },
    { key: 'NA', value: '纳米比亚' },
    { key: 'NR', value: '瑙鲁' },
    { key: 'NP', value: '尼泊尔' },
    { key: 'NL', value: '荷兰' },
    { key: 'AN', value: '荷属安的列斯' },
    { key: 'NC', value: '新喀里多尼亚' },
    { key: 'NZ', value: '新西兰' },
    { key: 'NI', value: '尼加拉瓜' },
    { key: 'NE', value: '尼日尔' },
    { key: 'NG', value: '尼日利亚' },
    { key: 'NU', value: '纽埃' },
    { key: 'NF', value: '诺福克岛' },
    { key: 'KP', value: '朝鲜民主主义人民共和国' },
    { key: 'XB', value: '北爱尔兰' },
    { key: 'MP', value: '北马里亚纳群岛' },
    { key: 'NO', value: '挪威' },
    { key: 'OM', value: '阿曼' },
    { key: 'PK', value: '巴基斯坦' },
    { key: 'PW', value: '帕劳' },
    { key: 'PA', value: '巴拿马' },
    { key: 'PG', value: '巴布亚新几内亚' },
    { key: 'PY', value: '巴拉圭' },
    { key: 'PE', value: '秘鲁' },
    { key: 'PH', value: '菲律宾' },
    { key: 'PN', value: '皮特凯恩' },
    { key: 'PL', value: '波兰' },
    { key: 'PT', value: '葡萄牙' },
    { key: 'PR', value: '波多黎各' },
    { key: 'QA', value: '卡塔尔' },
    { key: 'RE', value: '留尼汪' },
    { key: 'RO', value: '罗马尼亚' },
    { key: 'RU', value: '俄罗斯' },
    { key: 'RW', value: '卢旺达' },
    { key: 'LC', value: '圣卢西亚' },
    { key: 'SM', value: '圣马利诺' },
    { key: 'ST', value: '圣多美和普林西比' },
    { key: 'SA', value: '沙特阿拉伯' },
    { key: 'SN', value: '塞内加尔' },
    { key: 'SC', value: '塞舌尔' },
    { key: 'SL', value: '塞拉利昂' },
    { key: 'SG', value: '新加坡' },
    { key: 'SK', value: '斯洛伐克共和国' },
    { key: 'SI', value: '斯洛文尼亚' },
    { key: 'SB', value: '所罗门群岛' },
    { key: 'SO', value: '索马里' },
    { key: 'ZA', value: '南非' },
    { key: 'GS', value: '南乔治亚' },
    { key: 'ES', value: '西班牙' },
    { key: 'LK', value: '斯里兰卡' },
    { key: 'SH', value: '圣赫勒拿岛' },
    { key: 'KN', value: '圣克里斯多福及尼维斯' },
    { key: 'PM', value: '圣皮埃尔' },
    { key: 'VC', value: '圣文森特和格林纳丁斯' },
    { key: 'SD', value: '苏丹' },
    { key: 'SR', value: '苏里南' },
    { key: 'SJ', value: '斯瓦尔巴和扬马延' },
    { key: 'SZ', value: '史瓦济兰' },
    { key: 'SE', value: '瑞典' },
    { key: 'CH', value: '瑞士' },
    { key: 'SY', value: '阿拉伯叙利亚共和国' },
    { key: 'TW', value: '中国台湾' },
    { key: 'TJ', value: '塔吉克斯坦' },
    { key: 'TZ', value: '坦桑尼亚' },
    { key: 'TH', value: '泰国' },
    { key: 'TG', value: '多哥' },
    { key: 'TK', value: '托克劳' },
    { key: 'TO', value: '東加' },
    { key: 'TT', value: '特立尼达和多巴哥' },
    { key: 'TN', value: '突尼斯' },
    { key: 'TR', value: '土耳其' },
    { key: 'TM', value: '土库曼斯坦' },
    { key: 'TC', value: '特克斯和凯科斯群岛' },
    { key: 'TV', value: '图瓦卢' },
    { key: 'UM', value: '美国本土外小岛屿' },
    { key: 'UG', value: '乌干达' },
    { key: 'UA', value: '乌克兰' },
    { key: 'AE', value: '阿拉伯联合酋长国' },
    { key: 'GB', value: '英国' },
    { key: 'US', value: '美国' },
    { key: 'UY', value: '乌拉圭' },
    { key: 'UZ', value: '乌兹别克斯坦' },
    { key: 'VU', value: '瓦努阿图' },
    { key: 'VA', value: '梵蒂冈城国' },
    { key: 'VE', value: '委内瑞拉' },
    { key: 'VN', value: '越南' },
    { key: 'VG', value: '英属维京群岛' },
    { key: 'VI', value: '美属维京群岛' },
    { key: 'WF', value: '瓦利斯和富图纳群岛' },
    { key: 'EH', value: '西撒哈拉' },
    { key: 'WS', value: '萨摩亚' },
    { key: 'YE', value: '也门' },
    { key: 'YU', value: '南斯拉夫' },
    { key: 'ZM', value: '赞比亚' },
    { key: 'ZW', value: '津巴布韦' },
  ],
  es: [
    { key: 'AF', value: 'Afghanistan' },
    { key: 'AL', value: 'Albania' },
    { key: 'DZ', value: 'Algeria' },
    { key: 'AS', value: 'American Samoa' },
    { key: 'AD', value: 'Andorra' },
    { key: 'AO', value: 'Angola' },
    { key: 'AI', value: 'Anguilla' },
    { key: 'AQ', value: 'Antarctica' },
    { key: 'AG', value: 'Antigua and Barbuda' },
    { key: 'AR', value: 'Argentina' },
    { key: 'AM', value: 'Armenia' },
    { key: 'AW', value: 'Aruba' },
    { key: 'AU', value: 'Australia' },
    { key: 'AT', value: 'Austria' },
    { key: 'AZ', value: 'Azerbaijan' },
    { key: 'BS', value: 'Bahamas' },
    { key: 'BH', value: 'Bahrain' },
    { key: 'BD', value: 'Bangladesh' },
    { key: 'BB', value: 'Barbados' },
    { key: 'BY', value: 'Belarus' },
    { key: 'BE', value: 'Belgium' },
    { key: 'BZ', value: 'Belize' },
    { key: 'BJ', value: 'Benin' },
    { key: 'BM', value: 'Bermuda' },
    { key: 'BT', value: 'Bhutan' },
    { key: 'BO', value: 'Bolivia' },
    { key: 'BA', value: 'Bosnia and Herzegovina' },
    { key: 'BW', value: 'Botswana' },
    { key: 'BV', value: 'Bouvet Island' },
    { key: 'BR', value: 'Brazil' },
    { key: 'IO', value: 'British Indian Ocean Territory' },
    { key: 'WI', value: 'British West Indies' },
    { key: 'BN', value: 'Brunei Darussalam' },
    { key: 'BG', value: 'Bulgaria' },
    { key: 'BF', value: 'Burkina Faso' },
    { key: 'BU', value: 'Burma' },
    { key: 'BI', value: 'Burundi' },
    { key: 'KH', value: 'Cambodia' },
    { key: 'CM', value: 'Cameroon' },
    { key: 'CA', value: 'Canada' },
    { key: 'CV', value: 'Cape Verde' },
    { key: 'KY', value: 'Cayman Islands' },
    { key: 'CF', value: 'Central African Republic' },
    { key: 'TD', value: 'Chad' },
    { key: 'CL', value: 'Chile' },
    { key: 'CN', value: 'Chinese mainland' },
    { key: 'CX', value: 'Christmas Island' },
    { key: 'CC', value: 'Cocos (Keeling) Islands' },
    { key: 'CO', value: 'Colombia' },
    { key: 'KM', value: 'Comoros' },
    { key: 'CG', value: 'Democratic Republic of the Congo (Kinshasa)' },
    { key: 'CK', value: 'Cook Islands' },
    { key: 'CR', value: 'Costa Rica' },
    { key: 'CI', value: 'Ivory Coast' },
    { key: 'HR', value: 'Croatia' },
    { key: 'CU', value: 'Cuba' },
    { key: 'CY', value: 'Cyprus' },
    { key: 'CZ', value: 'Czech Republic' },
    { key: 'DK', value: 'Denmark' },
    { key: 'DJ', value: 'Djibouti' },
    { key: 'DM', value: 'Dominica' },
    { key: 'DO', value: 'Dominican Republic' },
    { key: 'TP', value: 'East Timor' },
    { key: 'EC', value: 'Ecuador' },
    { key: 'EG', value: 'Egypt' },
    { key: 'SV', value: 'El Salvador' },
    { key: 'GQ', value: 'Equatorial Guinea' },
    { key: 'ER', value: 'Eritrea' },
    { key: 'EE', value: 'Estonia' },
    { key: 'ET', value: 'Ethiopia' },
    { key: 'FO', value: 'Faroe Islands' },
    { key: 'FK', value: 'Falkland Islands' },
    { key: 'FJ', value: 'Fiji' },
    { key: 'FI', value: 'Finland' },
    { key: 'FR', value: 'France' },
    { key: 'PF', value: 'French Polynesia' },
    { key: 'TF', value: 'French Southern Territories' },
    { key: 'GA', value: 'Gabon' },
    { key: 'GM', value: 'Gambia' },
    { key: 'XA', value: 'Gaza' },
    { key: 'GE', value: 'Georgia' },
    { key: 'DE', value: 'Germany' },
    { key: 'GH', value: 'Ghana' },
    { key: 'GI', value: 'Gibraltar' },
    { key: 'GR', value: 'Great Britain' },
    { key: 'GL', value: 'Greece' },
    { key: 'GD', value: 'Greenland' },
    { key: 'GP', value: 'Grenada' },
    { key: 'GU', value: 'Guadeloupe' },
    { key: 'GT', value: 'Guam' },
    { key: 'GF', value: 'French Guiana' },
    { key: 'GN', value: 'Guatemala' },
    { key: 'GW', value: 'Guinea' },
    { key: 'GY', value: 'Guinea Bissau' },
    { key: 'HT', value: 'Guyana' },
    { key: 'HM', value: 'Haiti' },
    { key: 'XH', value: 'Held Territories' },
    { key: 'HN', value: 'Honduras' },
    { key: 'HK', value: 'Hong Kong SAR' },
    { key: 'HU', value: 'Hungary' },
    { key: 'IS', value: 'Iceland' },
    { key: 'IN', value: 'India' },
    { key: 'XI', value: 'Indian Ocean Islands' },
    { key: 'ID', value: 'Indonesia' },
    { key: 'IR', value: 'Iran (Islamic Republic of)' },
    { key: 'IQ', value: 'Iraq' },
    { key: 'IE', value: 'Ireland' },
    { key: 'IL', value: 'Isle of Man' },
    { key: 'IT', value: 'Israel' },
    { key: 'JM', value: 'Italy' },
    { key: 'JP', value: 'Jamaica' },
    { key: 'JO', value: 'Japan' },
    { key: 'KZ', value: 'Jordan' },
    { key: 'KE', value: 'Kazakhstan' },
    { key: 'KI', value: 'Kenya' },
    { key: 'KR', value: 'Kiribati' },
    { key: 'KW', value: 'Korea, Republic of (South Korea)' },
    { key: 'KG', value: 'Kuwait' },
    { key: 'LA', value: 'Kyrgyzstan' },
    { key: 'LV', value: "Lao, People's Democratic Republic" },
    { key: 'LB', value: 'Latvia' },
    { key: 'LS', value: 'Lebanon' },
    { key: 'LR', value: 'Lesotho' },
    { key: 'LY', value: 'Liberia' },
    { key: 'LI', value: 'Libya' },
    { key: 'LT', value: 'Liechtenstein' },
    { key: 'LU', value: 'Lithuania' },
    { key: 'MO', value: 'Luxembourg' },
    { key: 'MK', value: 'Macau SAR' },
    { key: 'MG', value: 'Macedonia, Rep. of' },
    { key: 'MW', value: 'Madagascar' },
    { key: 'MY', value: 'Malawi' },
    { key: 'MV', value: 'Malaysia' },
    { key: 'ML', value: 'Maldives' },
    { key: 'MT', value: 'Mali' },
    { key: 'MH', value: 'Malta' },
    { key: 'MQ', value: 'Marshall Islands' },
    { key: 'MR', value: 'Martinique' },
    { key: 'MU', value: 'Mauritania' },
    { key: 'YT', value: 'Mauritius' },
    { key: 'MX', value: 'Mayotte' },
    { key: 'FM', value: 'Mexico' },
    { key: 'MD', value: 'Micronesia, Federal States of' },
    { key: 'MC', value: 'Moldova, Republic of' },
    { key: 'MN', value: 'Monaco' },
    { key: 'MS', value: 'Montserrat' },
    { key: 'MA', value: 'Morocco' },
    { key: 'MZ', value: 'Mozambique' },
    { key: 'MM', value: 'Myanmar, Burma' },
    { key: 'NA', value: 'Namibia' },
    { key: 'NR', value: 'Nauru' },
    { key: 'NP', value: 'Nepal' },
    { key: 'NL', value: 'Netherlands' },
    { key: 'AN', value: 'Netherlands Antilles' },
    { key: 'NC', value: 'New Caledonia' },
    { key: 'NZ', value: 'New Zealand' },
    { key: 'NI', value: 'Nicaragua' },
    { key: 'NE', value: 'Niger' },
    { key: 'NG', value: 'Nigeria' },
    { key: 'NU', value: 'Niue' },
    { key: 'NF', value: 'Norfolk Island' },
    { key: 'KP', value: "Korea, Democratic People's Rep. (North Korea)" },
    { key: 'XB', value: 'Northern Ireland' },
    { key: 'MP', value: 'Northern Mariana Islands' },
    { key: 'NO', value: 'Norway' },
    { key: 'OM', value: 'Oman' },
    { key: 'PK', value: 'Pakistan' },
    { key: 'PW', value: 'Palau' },
    { key: 'PA', value: 'Panama' },
    { key: 'PG', value: 'Papua New Guinea' },
    { key: 'PY', value: 'Paraguay' },
    { key: 'PE', value: 'Peru' },
    { key: 'PH', value: 'Philippines' },
    { key: 'PN', value: 'Pitcairn Island' },
    { key: 'PL', value: 'Poland' },
    { key: 'PT', value: 'Portugal' },
    { key: 'PR', value: 'Puerto Rico' },
    { key: 'QA', value: 'Qatar' },
    { key: 'RE', value: 'Reunion Island' },
    { key: 'RO', value: 'Romania' },
    { key: 'RU', value: 'Russian Federation' },
    { key: 'RW', value: 'Rwanda' },
    { key: 'LC', value: 'Saint Lucia' },
    { key: 'SM', value: 'San Marino' },
    { key: 'ST', value: 'Sao Tome and Príncipe' },
    { key: 'SA', value: 'Saudi Arabia' },
    { key: 'SN', value: 'Senegal' },
    { key: 'SC', value: 'Seychelles' },
    { key: 'SL', value: 'Sierra Leone' },
    { key: 'SG', value: 'Singapore' },
    { key: 'SK', value: 'Slovakia (Slovak Republic)' },
    { key: 'SI', value: 'Slovenia' },
    { key: 'SB', value: 'Solomon Islands' },
    { key: 'SO', value: 'Somalia' },
    { key: 'ZA', value: 'South Africa' },
    { key: 'GS', value: 'South Georgia' },
    { key: 'ES', value: 'Spain' },
    { key: 'LK', value: 'Sri Lanka' },
    { key: 'SH', value: 'St. Helena' },
    { key: 'KN', value: 'Saint Kitts and Nevis' },
    { key: 'PM', value: 'Saint Pierre and Miquelon' },
    { key: 'VC', value: 'Saint Vincent and the Grenadines' },
    { key: 'SD', value: 'Sudan' },
    { key: 'SR', value: 'Suriname' },
    { key: 'SJ', value: 'Svalbard and Jan Mayen Islands' },
    { key: 'SZ', value: 'Swaziland' },
    { key: 'SE', value: 'Sweden' },
    { key: 'CH', value: 'Switzerland' },
    { key: 'SY', value: 'Syria, Syrian Arab Republic' },
    { key: 'TW', value: 'Taiwan China' },
    { key: 'TJ', value: 'Tajikistan' },
    { key: 'TZ', value: 'Tanzania' },
    { key: 'TH', value: 'Thailand' },
    { key: 'TG', value: 'Togo' },
    { key: 'TK', value: 'Tokelau' },
    { key: 'TO', value: 'Tonga' },
    { key: 'TT', value: 'Trinidad and Tobago' },
    { key: 'TN', value: 'Tunisia' },
    { key: 'TR', value: 'Turkey' },
    { key: 'TM', value: 'Turkmenistan' },
    { key: 'TC', value: 'Turks and Caicos Islands' },
    { key: 'TV', value: 'Tuvalu' },
    { key: 'UM', value: 'U.S. Minor Outlying Islands' },
    { key: 'UG', value: 'Uganda' },
    { key: 'UA', value: 'Ukraine' },
    { key: 'AE', value: 'United Arab Emirates' },
    { key: 'GB', value: 'United Kingdom' },
    { key: 'US', value: 'United States' },
    { key: 'UY', value: 'Uruguay' },
    { key: 'UZ', value: 'Uzbekistan' },
    { key: 'VU', value: 'Vanuatu' },
    { key: 'VA', value: 'Vatican City State (Holy See)' },
    { key: 'VE', value: 'Venezuela' },
    { key: 'VN', value: 'Vietnam' },
    { key: 'VG', value: 'Virgin Islands (British)' },
    { key: 'VI', value: 'Virgin Islands (U.S.)' },
    { key: 'WF', value: 'Wallis and Futuna Islands' },
    { key: 'EH', value: 'Western Sahara' },
    { key: 'WS', value: 'Samoa' },
    { key: 'YE', value: 'Yemen' },
    { key: 'YU', value: 'Yugoslavia' },
    { key: 'ZM', value: 'Zambia' },
    { key: 'ZW', value: 'Zimbabwe' },
  ],
  pt: [
    { key: 'AF', value: 'Afghanistan' },
    { key: 'AL', value: 'Albania' },
    { key: 'DZ', value: 'Algeria' },
    { key: 'AS', value: 'American Samoa' },
    { key: 'AD', value: 'Andorra' },
    { key: 'AO', value: 'Angola' },
    { key: 'AI', value: 'Anguilla' },
    { key: 'AQ', value: 'Antarctica' },
    { key: 'AG', value: 'Antigua and Barbuda' },
    { key: 'AR', value: 'Argentina' },
    { key: 'AM', value: 'Armenia' },
    { key: 'AW', value: 'Aruba' },
    { key: 'AU', value: 'Australia' },
    { key: 'AT', value: 'Austria' },
    { key: 'AZ', value: 'Azerbaijan' },
    { key: 'BS', value: 'Bahamas' },
    { key: 'BH', value: 'Bahrain' },
    { key: 'BD', value: 'Bangladesh' },
    { key: 'BB', value: 'Barbados' },
    { key: 'BY', value: 'Belarus' },
    { key: 'BE', value: 'Belgium' },
    { key: 'BZ', value: 'Belize' },
    { key: 'BJ', value: 'Benin' },
    { key: 'BM', value: 'Bermuda' },
    { key: 'BT', value: 'Bhutan' },
    { key: 'BO', value: 'Bolivia' },
    { key: 'BA', value: 'Bosnia and Herzegovina' },
    { key: 'BW', value: 'Botswana' },
    { key: 'BV', value: 'Bouvet Island' },
    { key: 'BR', value: 'Brazil' },
    { key: 'IO', value: 'British Indian Ocean Territory' },
    { key: 'WI', value: 'British West Indies' },
    { key: 'BN', value: 'Brunei Darussalam' },
    { key: 'BG', value: 'Bulgaria' },
    { key: 'BF', value: 'Burkina Faso' },
    { key: 'BU', value: 'Burma' },
    { key: 'BI', value: 'Burundi' },
    { key: 'KH', value: 'Cambodia' },
    { key: 'CM', value: 'Cameroon' },
    { key: 'CA', value: 'Canada' },
    { key: 'CV', value: 'Cape Verde' },
    { key: 'KY', value: 'Cayman Islands' },
    { key: 'CF', value: 'Central African Republic' },
    { key: 'TD', value: 'Chad' },
    { key: 'CL', value: 'Chile' },
    { key: 'CN', value: 'Chinese mainland' },
    { key: 'CX', value: 'Christmas Island' },
    { key: 'CC', value: 'Cocos (Keeling) Islands' },
    { key: 'CO', value: 'Colombia' },
    { key: 'KM', value: 'Comoros' },
    { key: 'CG', value: 'Democratic Republic of the Congo (Kinshasa)' },
    { key: 'CK', value: 'Cook Islands' },
    { key: 'CR', value: 'Costa Rica' },
    { key: 'CI', value: 'Ivory Coast' },
    { key: 'HR', value: 'Croatia' },
    { key: 'CU', value: 'Cuba' },
    { key: 'CY', value: 'Cyprus' },
    { key: 'CZ', value: 'Czech Republic' },
    { key: 'DK', value: 'Denmark' },
    { key: 'DJ', value: 'Djibouti' },
    { key: 'DM', value: 'Dominica' },
    { key: 'DO', value: 'Dominican Republic' },
    { key: 'TP', value: 'East Timor' },
    { key: 'EC', value: 'Ecuador' },
    { key: 'EG', value: 'Egypt' },
    { key: 'SV', value: 'El Salvador' },
    { key: 'GQ', value: 'Equatorial Guinea' },
    { key: 'ER', value: 'Eritrea' },
    { key: 'EE', value: 'Estonia' },
    { key: 'ET', value: 'Ethiopia' },
    { key: 'FO', value: 'Faroe Islands' },
    { key: 'FK', value: 'Falkland Islands' },
    { key: 'FJ', value: 'Fiji' },
    { key: 'FI', value: 'Finland' },
    { key: 'FR', value: 'France' },
    { key: 'PF', value: 'French Polynesia' },
    { key: 'TF', value: 'French Southern Territories' },
    { key: 'GA', value: 'Gabon' },
    { key: 'GM', value: 'Gambia' },
    { key: 'XA', value: 'Gaza' },
    { key: 'GE', value: 'Georgia' },
    { key: 'DE', value: 'Germany' },
    { key: 'GH', value: 'Ghana' },
    { key: 'GI', value: 'Gibraltar' },
    { key: 'GR', value: 'Great Britain' },
    { key: 'GL', value: 'Greece' },
    { key: 'GD', value: 'Greenland' },
    { key: 'GP', value: 'Grenada' },
    { key: 'GU', value: 'Guadeloupe' },
    { key: 'GT', value: 'Guam Bissau' },
    { key: 'GF', value: 'French Guiana' },
    { key: 'GN', value: 'Guatemala' },
    { key: 'GW', value: 'Guinea' },
    { key: 'GY', value: 'Guinea' },
    { key: 'HT', value: 'Guyana' },
    { key: 'HM', value: 'Haiti' },
    { key: 'XH', value: 'Held Territories' },
    { key: 'HN', value: 'Honduras' },
    { key: 'HK', value: 'Hong Kong SAR' },
    { key: 'HU', value: 'Hungary' },
    { key: 'IS', value: 'Iceland' },
    { key: 'IN', value: 'India' },
    { key: 'XI', value: 'Indian Ocean Islands' },
    { key: 'ID', value: 'Indonesia' },
    { key: 'IR', value: 'Iran (Islamic Republic of)' },
    { key: 'IQ', value: 'Iraq' },
    { key: 'IE', value: 'Ireland' },
    { key: 'IL', value: 'Isle of Man' },
    { key: 'IT', value: 'Israel' },
    { key: 'JM', value: 'Italy' },
    { key: 'JP', value: 'Jamaica' },
    { key: 'JO', value: 'Japan' },
    { key: 'KZ', value: 'Jordan' },
    { key: 'KE', value: 'Kazakhstan' },
    { key: 'KI', value: 'Kenya' },
    { key: 'KR', value: 'Kiribati' },
    { key: 'KW', value: 'Korea, Republic of (South Korea)' },
    { key: 'KG', value: 'Kuwait' },
    { key: 'LA', value: 'Kyrgyzstan' },
    { key: 'LV', value: "Lao, People's Democratic Republic" },
    { key: 'LB', value: 'Latvia' },
    { key: 'LS', value: 'Lebanon' },
    { key: 'LR', value: 'Lesotho' },
    { key: 'LY', value: 'Liberia' },
    { key: 'LI', value: 'Libya' },
    { key: 'LT', value: 'Liechtenstein' },
    { key: 'LU', value: 'Lithuania' },
    { key: 'MO', value: 'Luxembourg' },
    { key: 'MK', value: 'Macau SAR' },
    { key: 'MG', value: 'Macedonia, Rep. of' },
    { key: 'MW', value: 'Madagascar' },
    { key: 'MY', value: 'Malawi' },
    { key: 'MV', value: 'Malaysia' },
    { key: 'ML', value: 'Maldives' },
    { key: 'MT', value: 'Mali' },
    { key: 'MH', value: 'Malta' },
    { key: 'MQ', value: 'Marshall Islands' },
    { key: 'MR', value: 'Martinique' },
    { key: 'MU', value: 'Mauritania' },
    { key: 'YT', value: 'Mauritius' },
    { key: 'MX', value: 'Mayotte' },
    { key: 'FM', value: 'Mexico' },
    { key: 'MD', value: 'Micronesia, Federal States of' },
    { key: 'MC', value: 'Moldova, Republic of' },
    { key: 'MN', value: 'Monaco' },
    { key: 'MS', value: 'Montserrat' },
    { key: 'MA', value: 'Morocco' },
    { key: 'MZ', value: 'Mozambique' },
    { key: 'MM', value: 'Myanmar, Burma' },
    { key: 'NA', value: 'Namibia' },
    { key: 'NR', value: 'Nauru' },
    { key: 'NP', value: 'Nepal' },
    { key: 'NL', value: 'Netherlands' },
    { key: 'AN', value: 'Netherlands Antilles' },
    { key: 'NC', value: 'New Caledonia' },
    { key: 'NZ', value: 'New Zealand' },
    { key: 'NI', value: 'Nicaragua' },
    { key: 'NE', value: 'Niger' },
    { key: 'NG', value: 'Nigeria' },
    { key: 'NU', value: 'Niue' },
    { key: 'NF', value: 'Norfolk Island' },
    { key: 'KP', value: "Korea, Democratic People's Rep. (North Korea)" },
    { key: 'XB', value: 'Northern Ireland' },
    { key: 'MP', value: 'Northern Mariana Islands' },
    { key: 'NO', value: 'Norway' },
    { key: 'OM', value: 'Oman' },
    { key: 'PK', value: 'Pakistan' },
    { key: 'PW', value: 'Palau' },
    { key: 'PA', value: 'Panama' },
    { key: 'PG', value: 'Papua New Guinea' },
    { key: 'PY', value: 'Paraguay' },
    { key: 'PE', value: 'Peru' },
    { key: 'PH', value: 'Philippines' },
    { key: 'PN', value: 'Pitcairn Island' },
    { key: 'PL', value: 'Poland' },
    { key: 'PT', value: 'Portugal' },
    { key: 'PR', value: 'Puerto Rico' },
    { key: 'QA', value: 'Qatar' },
    { key: 'RE', value: 'Reunion Island' },
    { key: 'RO', value: 'Romania' },
    { key: 'RU', value: 'Russian Federation' },
    { key: 'RW', value: 'Rwanda' },
    { key: 'LC', value: 'Saint Lucia' },
    { key: 'SM', value: 'San Marino' },
    { key: 'ST', value: 'Sao Tome and Príncipe' },
    { key: 'SA', value: 'Saudi Arabia' },
    { key: 'SN', value: 'Senegal' },
    { key: 'SC', value: 'Seychelles' },
    { key: 'SL', value: 'Sierra Leone' },
    { key: 'SG', value: 'Singapore' },
    { key: 'SK', value: 'Slovakia (Slovak Republic)' },
    { key: 'SI', value: 'Slovenia' },
    { key: 'SB', value: 'Solomon Islands' },
    { key: 'SO', value: 'Somalia' },
    { key: 'ZA', value: 'South Africa' },
    { key: 'GS', value: 'South Georgia' },
    { key: 'ES', value: 'Spain' },
    { key: 'LK', value: 'Sri Lanka' },
    { key: 'SH', value: 'St. Helena' },
    { key: 'KN', value: 'Saint Kitts and Nevis' },
    { key: 'PM', value: 'Saint Pierre and Miquelon' },
    { key: 'VC', value: 'Saint Vincent and the Grenadines' },
    { key: 'SD', value: 'Sudan' },
    { key: 'SR', value: 'Suriname' },
    { key: 'SJ', value: 'Svalbard and Jan Mayen Islands' },
    { key: 'SZ', value: 'Swaziland' },
    { key: 'SE', value: 'Sweden' },
    { key: 'CH', value: 'Switzerland' },
    { key: 'SY', value: 'Syria, Syrian Arab Republic' },
    { key: 'TW', value: 'Taiwan China' },
    { key: 'TJ', value: 'Tajikistan' },
    { key: 'TZ', value: 'Tanzania' },
    { key: 'TH', value: 'Thailand' },
    { key: 'TG', value: 'Togo' },
    { key: 'TK', value: 'Tokelau' },
    { key: 'TO', value: 'Tonga' },
    { key: 'TT', value: 'Trinidad and Tobago' },
    { key: 'TN', value: 'Tunisia' },
    { key: 'TR', value: 'Turkey' },
    { key: 'TM', value: 'Turkmenistan' },
    { key: 'TC', value: 'Turks and Caicos Islands' },
    { key: 'TV', value: 'Tuvalu' },
    { key: 'UM', value: 'U.S. Minor Outlying Islands' },
    { key: 'UG', value: 'Uganda' },
    { key: 'UA', value: 'Ukraine' },
    { key: 'AE', value: 'United Arab Emirates' },
    { key: 'GB', value: 'United Kingdom' },
    { key: 'US', value: 'United States' },
    { key: 'UY', value: 'Uruguay' },
    { key: 'UZ', value: 'Uzbekistan' },
    { key: 'VU', value: 'Vanuatu' },
    { key: 'VA', value: 'Vatican City State (Holy See)' },
    { key: 'VE', value: 'Venezuela' },
    { key: 'VN', value: 'Vietnam' },
    { key: 'VG', value: 'Virgin Islands (British)' },
    { key: 'VI', value: 'Virgin Islands (U.S.)' },
    { key: 'WF', value: 'Wallis and Futuna Islands' },
    { key: 'EH', value: 'Western Sahara' },
    { key: 'WS', value: 'Samoa' },
    { key: 'YE', value: 'Yemen' },
    { key: 'YU', value: 'Yugoslavia' },
    { key: 'ZM', value: 'Zambia' },
    { key: 'ZW', value: 'Zimbabwe' },
  ],
};
