# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - sit

resources:
- repo: self

variables:
  - group: sitecore-xm-cloud-sit
  - group: sitecore-xm-cloud-edge-sit
  - group: alicloud-auth-dev
  - name: tag
    value: '$(Build.BuildNumber)' 
  - name: imageId
    value: 'registry-intl.cn-hongkong.aliyuncs.com/easthotels'
  - name: vmImageName
    value: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadSecureFile@1
      name: scjssconfig
      inputs:
        secureFile: 'scjssconfig-sit.json'
    - task: CmdLine@2
      inputs:
        script: |
          mv $(scjssconfig.secureFilePath) ./scjssconfig.json

    - task: Docker@2
      displayName: Docker Image Build
      inputs:
        containerRegistry: 'Alicloud Registry Connection Dev'
        repository: 'easthotels'
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        addPipelineData: false
        addBaseImageData: false
        arguments: '--build-arg SITECORE_API_HOST=$(XMC_SITECORE_API_HOST) --build-arg SITECORE_API_KEY=$(XMC_SITECORE_API_KEY) --build-arg SITECORE_EDGE_CONTEXT_ID=$(XMC_SITECORE_EDGE_CONTEXT_ID)'
        tags: '$(tag)'
    - task: CmdLine@2
      inputs:
        script: |
          echo 'Showing docker image'
          docker image ls
          echo 'Alicloud Registry Login'
          docker login --username=$(ALICLOUD_ACR_USERNAME) --password=$(ALICLOUD_ACR_PASSWORD) registry-intl.cn-hongkong.aliyuncs.com
          echo 'Retag docker tag'
          docker tag $(imageId):$(tag) registry-intl.cn-hongkong.aliyuncs.com/swirehotels/easthotels:$(tag)
          docker tag $(imageId):$(tag) registry-intl.cn-hongkong.aliyuncs.com/swirehotels/easthotels:latest
          echo 'Pushing docker image'
          docker push registry-intl.cn-hongkong.aliyuncs.com/swirehotels/easthotels:$(tag)
          docker push registry-intl.cn-hongkong.aliyuncs.com/swirehotels/easthotels:latest