import { AzureB2CProfile } from '@/utilities/SsoConstant';
import 'dotenv/config';
import fs from 'fs';
import path from 'path';

interface WellKnown {
  issuer: string;
  authorization_endpoint: string;
  token_endpoint: string;
  end_session_endpoint: string;
  jwks_uri: string;
  jwks?: { keys: { [propName: string]: unknown }[] };
}

const getWellKnownUrl = (tenant: string, userFlow: string, customDomain = true) => {
  return `https://${getAzureB2CDomain(tenant, customDomain)}/${tenant}.onmicrosoft.com/${userFlow}/v2.0/.well-known/openid-configuration`;
};

const getAzureB2CDomain = (tenant: string, customDomain = true) => {
  let loginDomain = `${tenant}.b2clogin.com`;
  if (customDomain && process.env.AZURE_AD_B2C_AUTH_DOMAIN) {
    loginDomain = process.env.AZURE_AD_B2C_AUTH_DOMAIN;
  }
  return loginDomain;
};

const getWellKnownJson = async (
  tenant: string,
  userFlow: string,
  customDomain = true
): Promise<WellKnown> => {
  const url = getWellKnownUrl(tenant, userFlow, customDomain);
  console.log(`Load from url: ${url}`);
  const result = await fetch(url);
  const data: WellKnown = await result.json();
  data.jwks = await getKeys(data.jwks_uri);
  return data;
};

const getKeys = async (jwks_uri: string) => {
  console.log(`Load from url: ${jwks_uri}`);
  const result = await fetch(jwks_uri);
  const data = await result.json();
  return data;
};

(async () => {
  const tenant = process.env.AZURE_AD_B2C_TENANT_NAME || AzureB2CProfile.AZURE_AD_B2C_TENANT_NAME;
  const wellKnonwDatas: Record<string, WellKnown> = {};
  try {
    const flowMappings: Record<string, string | undefined> = {
      azureb2c: AzureB2CProfile.AZURE_AD_B2C_PRIMARY_USER_FLOW,
      'azureb2c-phone': AzureB2CProfile.AZURE_AD_B2C_PHONE_USER_FLOW,
      'azureb2c-pwd': process.env.AZURE_AD_B2C_AUTOLOGIN_USER_FLOW,
    };
    for (const providerName in flowMappings) {
      const flow = flowMappings[providerName];
      if (flow) {
        wellKnonwDatas[`${providerName}`] = await getWellKnownJson(tenant, flow);
        wellKnonwDatas[`default-${providerName}`] = await getWellKnownJson(tenant, flow, false);
      }
    }
    const userFlows = [process.env.AZURE_AD_B2C_PWD_USER_FLOW];
    for (let i = 0; i < userFlows.length; i++) {
      const v = userFlows[i];
      try {
        if (v) {
          const flow = v.toLowerCase();
          wellKnonwDatas[`azureb2c-${flow}`] = await getWellKnownJson(tenant, v);
          wellKnonwDatas[`default-azureb2c-${flow}`] = await getWellKnownJson(tenant, v, false);
        }
      } catch (ex) {
        console.log(ex);
      }
    }
  } catch (e) {
    console.log(e);
  }
  writeData(wellKnonwDatas);
})();

function writeData(data: Record<string, WellKnown>): void {
  console.log('Write WellKnown', data);
  const configPath = path.resolve('src/temp/wellknown.js');

  let dataText = `/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.\n`;
  dataText += `const wellknown = ${JSON.stringify(data, null, 2)};`;
  dataText += `\nmodule.exports = wellknown;`;

  console.log(`Writing runtime config to ${configPath}`);
  fs.writeFileSync(configPath, dataText, { encoding: 'utf8' });
}
